services:
  - type: worker
    name: multilang-translate-bot
    env: python
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    autoDeploy: false
